### ISSUE TITLE
The variable '$defaultNSXConnection' cannot be retrieved because it has not been set

### ISSUE THREAD

**Issue by dcvlehr** [vmware/powernsx#616]
When attempting to connect to the NSX manager, I get this error.

The variable '$defaultNSXConnection' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\PowerNSX\3.0.1174\PowerNSX.psm1:25305 char:41
+             [PSCustomObject]$Connection=$defaultNSXConnection
+                                         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (defaultNSXConnection:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

**Comment by alagoutte** [comment]
What command do you are using ?

**Comment by dcvlehr** [comment]
Connect-NsxServer -vCenterServer ServerName.com

I've tried by IP address as well. Docs said -vCenterServer was prefered. I also have the powercli module installed, and the connect-NsxServer cmdlet will also try to use an existing vSphere connection and automatically attempts to hit the correct NSX manager IP without ever referencing it

**Comment by alagoutte** [comment]
Strange
what release of PowerShell ? do you have try a older release ?

**Comment by dcvlehr** [comment]
```
Name                           Value                                                                                                                           
----                           -----                                                                                                                           
PSVersion                      5.1.17134.858                                                                                                                   
PSEdition                      Desktop                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                         
BuildVersion                   10.0.17134.858                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                 
WSManStackVersion              3.0                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                             
SerializationVersion           1.1.0.1 
```

**Comment by dcvlehr** [comment]
now I'm getting the following:

```
Connect-NsxServer -vCenterServer esx01
Using existing PowerCLI connection to 10.x.x.x
Connection to NSX server 10.x.x.x failed : System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the 
SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Program Files\WindowsPowerShell\Modules\PowerNSX\3.0.1174\PowerNSX.psm1:4939 char:13
+             Throw "Connection to NSX server $NsxServer failed : $_"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Connection to N...ProcessRecord():String) [], RuntimeException
    + FullyQualifiedErrorId : Connection to NSX server 10.x.x.x failed : System.Net.WebException: The underlying connection was closed: Could not establ 
   ish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid acco  
  rding to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
 

```

**Comment by alagoutte** [comment]
What NSX Release ?

you try to connect directly to NSX Manager ?

**Comment by dcvlehr** [comment]
```
Version    Name                                Repository           Description                                                                                
-------    ----                                ----------           -----------                                                                                
3.0.1174   PowerNSX                            PSGallery            PowerNSX is a PowerShell module that abstracts the VMware NSX API to a set of easily use...
```

I've tried Connect-NsxServer -NsxServer 10.X.X.X -Credential $cred 

Still won't work.

**Comment by dcvlehr** [comment]
I am now able, without PowerNSX at all, to connect to my NSX manager via pure powershell invoke-restmethod

```
#logon credentials
$username = 'me'
$password = Get-Content "C:\Users\myuser\Desktop\vcenterpassword.txt" | ConvertTo-SecureString
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $password

#format credentials
$auth = [System.Convert]::ToBase64String([System.Text.ASCIIEncoding]::ASCII.GetBytes($Credential.UserName+':'+$Credential.GetNetworkCredential().Password))
$head = @{'Authorization' = "Basic $auth"}

#API URI to conenct to
$URI = "https://10.x.x.x/api/2.0/services/securitytags/tag/securitytag-13"

#send API call
$request = Invoke-RestMethod -Uri $URI -Method Get -Headers $head
$request
```
This returns a security tag just as it did when using Postman. Still have no idea why powerNSX doesn't work. Was really hoping to abstract some of this.

**Comment by dcvlehr** [comment]
Now confused again...rebooted computer and now I can't get an API call in either to NSX manager.

```
Invoke-RestMethod : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
At line:13 char:12
+ $request = Invoke-RestMethod -Uri $URI -Method Get -Headers $head
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by alagoutte** [comment]
> 
> 
> ```
> Version    Name                                Repository           Description                                                                                
> -------    ----                                ----------           -----------                                                                                
> 3.0.1174   PowerNSX                            PSGallery            PowerNSX is a PowerShell module that abstracts the VMware NSX API to a set of easily use...
> ```
> 
> I've tried Connect-NsxServer -NsxServer 10.X.X.X -Credential $cred
> 
> Still won't work.

i ask the NSX Manager release

**Comment by alagoutte** [comment]
and for your issue about SSL/TLS it is coming from need to disable certificate check (it is set automatically when launch connect-nsx...)

**Comment by dcvlehr** [comment]
NSX Manager Version: | 6.4.5 Build 13282012

I can get around the TLS issue easy enough. Just wish I could actually use powernsx >.<

**Comment by alagoutte** [comment]
You are using the vCenter name when connect ? (and the administrator@vsphere.local) account ? (not the NSX Manager)

**Comment by dcvlehr** [comment]
So that worked with those credentials...how am I able to make any API call I want outside of powernsx with my admin credentials, but using powernsx requires this specific account?

**Comment by alagoutte** [comment]
you can the use admin account of NSX Manager ? or a another account on vSphere ?

**Comment by dcvlehr** [comment]
I have been making API calls to NSX directly with my personal admin account. I was finally able to do it with the power nsx module using the adminstrator@vsphere.local
